apiVersion: apps/v1 
kind: Deployment                                              # Type of the kubernetes resource
metadata:
  name: api-deployment                                   # Name of the Kubernetes resource
  labels:
    app: go-store-api
spec:
  replicas: 1                                                 # Number of pods to run at any given time
  selector:
    matchLabels: 
      app: go-store-api                                # This deployment applies to any Pods matching the specified label
  template:                                                   # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                                                 # The labels that will be applied to all of the pods in this deployment
        app: go-store-api                              
    spec:                                                     # Spec for the container which will run in the Pod
      containers:
      - name: go-store-cont
        image: raghavi101/go-api:1.0                  
        imagePullPolicy: IfNotPresent 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
                         
        ports:
          - name: http
            containerPort: 8080                               # Should match the port number that the Go application listens on
        envFrom:
          - secretRef:
              name: mysql-secret